// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppSetting: typeof import('./src/components/AppSetting.vue')['default']
    ChartHeatmapCartesian: typeof import('./src/components/ChartHeatmapCartesian.vue')['default']
    ChartTreemap: typeof import('./src/components/ChartTreemap.vue')['default']
    ElAnchor: typeof import('element-plus/es')['ElAnchor']
    ElAnchorLink: typeof import('element-plus/es')['ElAnchorLink']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElStatistic: typeof import('element-plus/es')['ElStatistic']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElText: typeof import('element-plus/es')['ElText']
    FilterSelect: typeof import('./src/components/FilterSelect.vue')['default']
    LayoutHeader: typeof import('./src/components/LayoutHeader.vue')['default']
    Opener: typeof import('./src/components/Opener.vue')['default']
    ReqMgmtCtrlf: typeof import('./src/components/ReqMgmtCtrlf.vue')['default']
    ReqMgmtFooter: typeof import('./src/components/ReqMgmtFooter.vue')['default']
    ReqMgmtList: typeof import('./src/components/ReqMgmtList.vue')['default']
    ReqMgmtListTable: typeof import('./src/components/ReqMgmtListTable.vue')['default']
    ReqMgmtProjectManager: typeof import('./src/components/ReqMgmtProjectManager.vue')['default']
    ReqMgmtProjectManagerAdd: typeof import('./src/components/ReqMgmtProjectManagerAdd.vue')['default']
    ReqMgmtSide: typeof import('./src/components/ReqMgmtSide.vue')['default']
    ReqMgmtStatistic: typeof import('./src/components/ReqMgmtStatistic.vue')['default']
    ToggleDark: typeof import('./src/components/ToggleDark.vue')['default']
    WebsiteOpener: typeof import('./src/components/WebsiteOpener.vue')['default']
  }
}
